#!/bin/bash

clear

GREPFILTER=${2:-'all'}
NUMBERLINES=${3:-15}
REFRESHTIME=${1:-3} 
          
while true
do
        stty -echo      
        printf "%s\n\n" "$(date)"

	top_out=$(top -bn 1)
	free_out=$(free -h)
             
        echo "$top_out" | grep 'Cpu(s)' | awk '{ printf("CPU utilization = \t %-4s %% \033[K \n", (100-$8) ); }'  | head -n 1
        echo "$free_out" | grep -w -F 'Mem: ' | awk '{ printf("MEM free        = \t %-4s %% \033[K \n", (100*$4/$2) ); }'
    
        printf '\n'

        if [ "$GREPFILTER" = 'all' ]
                then
                        echo "$top_out" | grep '^ ' | awk '{ printf("\033[4m%-8s  %-8s  %-8s  %-8s  %-8s %-8s  \033[m  \n", $1, $2, $8, $9, $10, $12); }'  | head -n 1
                        echo "$top_out" | grep '^ ' | awk '{ printf("%-8s  %-8s  %-8s  %-8s  %-8s  %-8s \033[K \n", $1, $2, $8, $9, $10, $12); }' | head -n $((++NUMBERLINES)) | tail -n $NUMBERLINES
        fi
        if [ "$GREPFILTER" != 'all' ]
                then
                        echo "$top_out" | grep '^ ' | awk '{ printf("\033[4m%-8s  %-8s  %-8s  %-8s  %-8s %-8s  \033[m  \n", $1, $2, $8, $9, $10, $12); }'  | head -n 1
                        echo "$top_out" | grep $GREPFILTER | awk '{ printf("%-8s  %-8s  %-8s  %-8s  %-8s  %-8s \033[K \n", $1, $2, $8, $9, $10, $12); }' | head -n $((++NUMBERLINES)) | tail -n $NUMBERLINES
        fi
        printf '\n'
        echo "$free_out" | head -n 1 | awk '{ printf("\t  %-8s  %-8s  %-8s  \033[K \n", $1, $2, $3); }'
        echo "$free_out" | grep -w -F 'Mem: ' | awk '{ printf("%-8s  %-8s  %-8s  %-8s  \033[K \n", $1, $2, $3, $4); }'
        echo "$free_out" | grep -w -F 'Swap: ' | awk '{ printf("%-8s  %-8s  %-8s  %-8s  \033[K \n", $1, $2, $3, $4); }'
        sleep $REFRESHTIME

        printf '\033[H'
        stty echo
done
